### ISSUE TITLE
Some issues in viewmodel layer

### ISSUE THREAD

**Issue by luongvo** [anticafe/survey_app#22]
- VIEW is handling quite many logics, instead of knowing the Result data from the network/repository layer, it should be converted at ViewModel and sending back to View with a UI display data class only, it would reduce the logic to check for the current state like this: https://github.com/anticafe/survey_app/blob/4c79d8fc64347199a6648c19d576425d2ab8b694/app/src/main/java/com/myapp/ui/main/MainFragment.kt#L62
- Is that correct to init the first loading page from 1 instead of 0?

**Comment by trietbui85** [comment]
Hi @luongvo 

>Is that correct to init the first loading page from 1 instead of 0?

My mistake, because when reading the *Technical Test* documentation, there is a sample request which has page number starts from 1 (`https://nimble-survey-api.herokuapp.com/surveys.json?page=1&per_page=10`). That's why I misunderstand that page number will be from 1 too. 
Fixed in 981ddba.

I also moved all remaining logic of Loading (fullscreen & load more) into ViewModel too in 
c1e8211.
