### ISSUE TITLE
Some issues in view layer

### ISSUE THREAD

**Issue by luongvo** [anticafe/survey_app#23]
- https://github.com/anticafe/survey_app/blob/4c79d8fc64347199a6648c19d576425d2ab8b694/app/src/main/java/com/myapp/ui/main/SurveyAdapter.kt#L43 Use DiffUtil, notifyDataSetChanged is expensive in case we are appending items.
- Naming convention: "mCallback" https://github.com/anticafe/survey_app/blob/4c79d8fc64347199a6648c19d576425d2ab8b694/app/src/main/java/com/myapp/ui/main/SurveyAdapter.kt#L17
- `newInstance` for `MainFragment`?
- This looks odd to me: https://github.com/anticafe/survey_app/blob/4c79d8fc64347199a6648c19d576425d2ab8b694/app/src/main/java/com/myapp/ui/detail/DetailFragment.kt#L47 actually he can just set it at Fragment's onViewCreated()
- This can be an extended field
in the same entity class: https://github.com/anticafe/survey_app/blob/4c79d8fc64347199a6648c19d576425d2ab8b694/app/src/main/java/com/myapp/utils/TextExt.kt#L10

**Comment by trietbui85** [comment]
Hi @luongvo 
Thanks for your code review. I think some of above issues has been fixed before yesterday.
> private var mCallback: MainFragment.OpenDetailCallback = callback 

It's improved 2 days ago: 
https://github.com/anticafe/survey_app/blob/bbb97216c6bd87bd29c9f7fe857811fa3d5e3859/app/src/main/java/com/myapp/ui/main/SurveyAdapter.kt#L16

And about this:
> requireActivity().onBackPressedDispatcher.addCallback(this, callback) 
>actually he can just set it at Fragment's onViewCreated()

It's been improved by using NavComponent already in commit bbb9721
https://github.com/anticafe/survey_app/blob/bbb97216c6bd87bd29c9f7fe857811fa3d5e3859/app/src/main/java/com/myapp/ui/detail/DetailFragment.kt#L39-L47

**Comment by trietbui85** [comment]
Well I see. According to @luongvo 's [comment](https://github.com/anticafe/survey_app/issues/24#issuecomment-584030125), you take the revision based on submission date, thus this issue still there. However, now these below issues have been fixed:
>private var mCallback: MainFragment.OpenDetailCallback = callback

Fixed in bbb9721

And for this one, fixed in bbb9721
>requireActivity().onBackPressedDispatcher.addCallback(this, callback)
>actually he can just set it at Fragment's onViewCreated()

**Comment by trietbui85** [comment]
Just a little comment about onBackPressed. Now I use NavComponent to handle that onBackPressed so that is ok. But before:
>requireActivity().onBackPressedDispatcher.addCallback(this, callback)
>actually he can just set it at Fragment's onViewCreated()

@luongvo, according to your comment, it should be in `onViewCreated`. However, at first I follow Android official document ([Provide custom back navigation](https://developer.android.com/guide/navigation/navigation-custom-back)) and they let me know from `onCreate` is fine too.

**Comment by trietbui85** [comment]
>This can be an extended field in the same entity class: 4c79d8f

Fixed in b47eb2c

**Comment by trietbui85** [comment]
About RecyclerView issue
>Use DiffUtil, notifyDataSetChanged is expensive in case we are appending items. Commit 4c79d8f

Fixed in 8af0391

**Comment by trietbui85** [comment]
All issues has been fixed. Please help me to verify. Your comments are welcome 👍 .
